### ISSUE TITLE
[1.20.1] Crash when using Sinytra Connector

### ISSUE THREAD

**Issue by Doctor-Duck** [AbdElAziz333/Saturn#17]
I am using the 0.0.5 version of Saturn and I am encountering the following error while using the  1.0.0-beta.15+1.20.1-full version the Sinytra Connector mod.

[15:50:52] [pool-4-thread-1/FATAL]: Mixin apply for mod (unknown) failed saturn.mixins.json:world.temperature_cache.BiomeMixin from mod (unknown) -> net.minecraft.world.level.biome.Biome: io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method m_47505_ in saturn.mixins.json:world.temperature_cache.BiomeMixin from mod (unknown) cannot reduce visibiliy of PUBLIC target method
io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method m_47505_ in saturn.mixins.json:world.temperature_cache.BiomeMixin from mod (unknown) cannot reduce visibiliy of PUBLIC target method
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:479) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:452) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23577!/:1.0.0-beta.15+1.20.1]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.world.level.biome.FixedBiomeSource.<clinit>(FixedBiomeSource.java:17) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at net.minecraft.world.level.biome.BiomeSources.m_220586_(BiomeSources.java:8) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.m_258029_(BuiltInRegistries.java:448) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.m_258037_(BuiltInRegistries.java:462) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.core.registries.BuiltInRegistries.m_257453_(BuiltInRegistries.java:461) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.m_257498_(BuiltInRegistries.java:455) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:55) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%231001!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Doctor-Duck** [comment]
If I disable the Sinytra Connector mod, then I get the same error from issue #15

**Comment by AbdElAziz333** [comment]
Can you please use the new update?
[1.18.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.18.2-0.0.6) - [1.19.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.2-0.0.6) - [1.19.3](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.3-0.0.6) - [1.19.4](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.19.4-0.0.6) - [1.20.1](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.20.1-0.0.6) - [1.20.2](https://github.com/AbdElAziz333/Saturn/releases/tag/mc1.20.2-0.0.6)

**Comment by Doctor-Duck** [comment]
The crash no longer occurs. I am however unsure if  Saturn has had an impact at reducing the amount of memory that is being used up by Forge/Minecraft.

**Comment by AbdElAziz333** [comment]
i will add performance benchmarks as soon a possible.
